# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/jasper/Dropbox/C++/Final Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/jasper/Dropbox/C++/Final Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jasper/Dropbox/C++/Final Project/CMakeFiles" "/home/jasper/Dropbox/C++/Final Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jasper/Dropbox/C++/Final Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TronSnake

# Build rule for target.
TronSnake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TronSnake
.PHONY : TronSnake

# fast build rule for target.
TronSnake/fast:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/build
.PHONY : TronSnake/fast

Entity.o: Entity.cpp.o
.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i
.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s
.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

Tail.o: Tail.cpp.o
.PHONY : Tail.o

# target to build an object file
Tail.cpp.o:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Tail.cpp.o
.PHONY : Tail.cpp.o

Tail.i: Tail.cpp.i
.PHONY : Tail.i

# target to preprocess a source file
Tail.cpp.i:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Tail.cpp.i
.PHONY : Tail.cpp.i

Tail.s: Tail.cpp.s
.PHONY : Tail.s

# target to generate assembly for a file
Tail.cpp.s:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/Tail.cpp.s
.PHONY : Tail.cpp.s

mainTest.o: mainTest.cpp.o
.PHONY : mainTest.o

# target to build an object file
mainTest.cpp.o:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/mainTest.cpp.o
.PHONY : mainTest.cpp.o

mainTest.i: mainTest.cpp.i
.PHONY : mainTest.i

# target to preprocess a source file
mainTest.cpp.i:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/mainTest.cpp.i
.PHONY : mainTest.cpp.i

mainTest.s: mainTest.cpp.s
.PHONY : mainTest.s

# target to generate assembly for a file
mainTest.cpp.s:
	$(MAKE) -f CMakeFiles/TronSnake.dir/build.make CMakeFiles/TronSnake.dir/mainTest.cpp.s
.PHONY : mainTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... TronSnake"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... Tail.o"
	@echo "... Tail.i"
	@echo "... Tail.s"
	@echo "... mainTest.o"
	@echo "... mainTest.i"
	@echo "... mainTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

